#!/bin/bash

#Run logistic regression classification on a set of input files using R. Takes 3 inputs: GM, WM, and CSF directories

GM_dir=$1 #First user input is directory containing GM mnc files
WM_dir=$2 #Second user input is directory containing WM mnc files
CSF_dir=$3 #Third user input is directory containing CSF mnc files

#Set up directories for 2x and 4x downsampled data
mkdir -p ${GM_dir}_dwnsampld_2
mkdir -p ${WM_dir}_dwnsampld_2
mkdir -p ${CSF_dir}_dwnsampld_2

GM_2=${GM_dir}_dwnsampld_2
WM_2=${WM_dir}_dwnsampld_2
CSF_2=${CSF_dir}_dwnsamld_2

mkdir -p ${GM_dir}_dwnsampld_4
mkdir -p ${WM_dir}_dwnsampld_4
mkdir -p ${CSF_dir}_dwnsampld_4

GM_4=${GM_dir}_dwnsampld_4
WM_4=${WM_dir}_dwnsampld_4
CSF_4=${CSF_dir}_dwnsamld_4

#Downsample data by 2 or 4 in each dimension
for dir in $GM_dir $WM_dir $CSF_dir; do
	for file in dir/*; do 
		mincresample -clob -step 2 2 2 -size 94 116 98 -zstart -90 $file ${dir}_dwnsampld_2/$(basename $file) #Downsample by 2 in each dimension & crop image. Store in appropriate directory. 
		mincresample -clob -step 4 4 4 -size 47 58 49 -zstart -90 $file ${dir}_dwnsampld_4/$(basename $file) #Downsample by 4 in each dimension & crop image. Store in appropriate directory. 
	done
done

#Call logistic regression R script
./logistic_regression.R 


