#!/bin/bash

#Run logistic regression classification on a set of input files using R

GM_dir=$1 #First user input is directory containing GM mnc files
WM_dir=$2 #Second user input is directory containing WM mnc files
CSF_dir=$3 #Third user input is directory containing CSF mnc files

#Set up directories for 2x and 4x downsampled data
mkdir ${GM_dir}_dwnsampld_2
#mkdir ${WM_dir}_dwnsampld_2
#mkdir ${CSF_dir}_dwnsampld_2

GM_2=${GM_dir}_dwnsampld_2
WM_2=${WM_dir}_dwnsampld_2
CSF_2=${CSF_dir}_dwnsamld_2

#mkdir ${GM_dir}_dwnsampld_4
#mkdir ${WM_dir}_dwnsampld_4
#mkdir ${CSF_dir}_dwnsampld_4

GM_4=${GM_dir}_dwnsampld_4
WM_4=${WM_dir}_dwnsampld_4
CSF_4=${CSF_dir}_dwnsamld_4

#for dir in $GM_dir $WM_dir $CSF_dir; do
#	for file in dir/*; do 
#		echo mincresample -clob -step 2 2 2 -size 94 116 98 -zstart -90 $file $dir/$(basename $file)
#		echo mincresample -clob -step 4 4 4 -size 47 58 49 -zstart -90 $file $dir/$(basename $file)
#	done
#done
